// <auto-generated />
using System;
using Game.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Quest.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Game.Model.HeroAttribute", b =>
                {
                    b.Property<int>("HeroAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Dex")
                        .HasColumnType("REAL");

                    b.Property<double>("Exp")
                        .HasColumnType("REAL");

                    b.Property<double>("Hp")
                        .HasColumnType("REAL");

                    b.Property<double>("Mana")
                        .HasColumnType("REAL");

                    b.Property<double?>("Str")
                        .HasColumnType("REAL");

                    b.HasKey("HeroAttributeId");

                    b.ToTable("HeroAttributes");
                });

            modelBuilder.Entity("Game.Model.HeroClassModel", b =>
                {
                    b.Property<int>("HeroClassModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroAttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroClassName")
                        .HasColumnType("TEXT");

                    b.HasKey("HeroClassModelId");

                    b.HasIndex("HeroAttributeId");

                    b.ToTable("HeroClasses");
                });

            modelBuilder.Entity("Game.Model.HeroClassModel", b =>
                {
                    b.HasOne("Game.Model.HeroAttribute", "HeroAttribute")
                        .WithMany("HeroClassModels")
                        .HasForeignKey("HeroAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroAttribute");
                });

            modelBuilder.Entity("Game.Model.HeroAttribute", b =>
                {
                    b.Navigation("HeroClassModels");
                });
#pragma warning restore 612, 618
        }
    }
}
